---
- name: Create Traefik Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_data_directory }}"

- name: Template Traefik config.yml
  template:
    src: "{{ item }}"
    mode: 0644
    dest: "{{ traefik_data_directory }}/{{ item }}"
  loop:
    - config.yml
    - traefik.yml
    - docker-compose.yml
    - acme.json
  register: template_config

- name: chmod acme.json
  file:
    path: "{{ traefik_data_directory }}/acme.json"
    mode: '0600'

- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: "{{ traefik_data_directory }}/"
    files:
      - docker-compose.yml
